.TH OPENQRM-EXECD 1

.SH NAME openqrm-execd \- The openQRM execution daemon

.SH SYNOPSIS openqrm-execd

.SH DESCRIPTION \fIopenqrm-execd\fP is the openQRM remove execution daemon.

.PP It was written for http://www.openqrm.org

.SH COPYRIGHT Copyright 2014, openQRM Enterprise GmbH

openQRM Enterprise developed by openQRM Enterprise GmbH.
All source code and content (c) Copyright 2014, openQRM Enterprise GmbH unless specifically noted otherwise.
This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
The latest version of this license can be found here: src/doc/LICENSE.txt
By using this software, you acknowledge having read this license and agree to be bound thereby.

.SH AUTHORS openQRM Enterprise GmbH
E-mail :  <info@openqrm-enterprise.com>
