#!/bin/bash
# this script helps the "make" to call functions 
# from within the Makefile
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2014, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#

OPENQRM_SERVER_BASE_DIR=`pwd`/`dirname $0`
OPENQRM_SOURCE_DIR=$OPENQRM_SERVER_BASE_DIR
. $OPENQRM_SOURCE_DIR/etc/openqrm-server.conf
. $OPENQRM_SOURCE_DIR/include/openqrm-functions
. $OPENQRM_SOURCE_DIR/include/openqrm-build-functions
. $OPENQRM_SOURCE_DIR/include/openqrm-package-functions
MAKE_COMMAND=$1

if [ "$MAKE_COMMAND" == "" ]; then
	echo "This script helps the "make" to call functions from within the Makefiles"
	exit 0
fi

$@
