#!/usr/bin/perl -w
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2014, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#
use strict;
my ($plain) = @ARGV;
my $itoa64 = './0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
my $salt;
for (1..2) { $salt .= substr $itoa64, rand(length($itoa64)), 1; }
my $password = crypt($plain, $salt);

print "<\?php\n";
print "\$thisfile = basename(\$_SERVER['PHP_SELF']);\n";
print "echo \"$password\";\n";
print "unlink(\$thisfile);\n";
print "\?>\n";




